server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  main:
    web-application-type: reactive
  application:
    name: pefacil-api-gateway-zuul
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pefacil-product
          uri: lb://pefacil-product
          predicates:
            - Path=/pefacil-product/**


